from django.urls import path
from finer import views

urlpatterns = [
    path('', views.home, name='index'),
    path('user_register', views.create_user, name='create_user'),
    path('user_home/', views.user_home, name='user_home'),
    path('logout/', views.logout, name='logout'),
    path('churidar', views.churidar, name='churidar'),
    path('view_orders/', views.view_orders, name='view_orders'),
    path('saree', views.saree, name='saree'),
    path('order_confirm/<str:order_date>/', views.order_confirm, name='order_confirm'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/<str:total_amount>/', views.checkout, name='checkout'),
    path('update_cart', views.update_cart, name='update_cart'),
    path('user_feedback/', views.user_feedback, name='user_feedback'),
    path('feedback_details/', views.feedback_details, name='feedback_details'),
    path('cart', views.cart, name='cart'),
    path('shirt', views.shirt, name='shirt'),
    path('tshirt', views.tshirt, name='tshirt'),
    path('get_subtypes/', views.get_subtypes, name='get_subtypes'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('pages-login', views.login, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('admin_login', views.admin, name='admin'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_login/addproduct/', views.product, name='product'),
    path('registered_users/', views.registered_users, name='registered_users'),
    path('view_products/', views.view_products, name='view_products'),
    path('add_product/', views.add_product, name='add_product'),
    path('shirt_collection/', views.shirt_collection, name='shirt_collection'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
]
