# Generated by Django 5.0 on 2023-12-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0003_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
