# Generated by Django 5.0 on 2023-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0004_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
