# Generated by Django 5.0 on 2023-12-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
