# Generated by Django 5.0 on 2023-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
