# Generated by Django 5.0 on 2023-12-16 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0010_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finer.product'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finer.user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
