# Generated by Django 5.0 on 2023-12-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0012_rename_uid_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='subtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
