# Generated by Django 5.0 on 2023-12-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0013_remove_product_image_product_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
