# Generated by Django 5.0 on 2023-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0014_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
