# Generated by Django 5.0 on 2023-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0015_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_mode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
