# Generated by Django 5.0 on 2024-01-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
