# Generated by Django 5.0 on 2024-01-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0018_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='products',
        ),
    ]
