# Generated by Django 5.0 on 2024-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0020_remove_shippingaddress_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
            ],
        ),
    ]
