# Generated by Django 5.0 on 2024-01-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0021_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
