# Generated by Django 5.0 on 2024-01-12 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0022_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
