# Generated by Django 5.0 on 2024-01-13 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0023_shippingaddress_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finer.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finer.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finer.product')),
            ],
        ),
    ]
