# Generated by Django 5.0 on 2024-01-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finer', '0024_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
